name: CI/CD Pipeline

on:
  push:
    branches:
      # trigger workflow when code is pushed
      - main
  pull_request:
    branches:
      # trigger workflow when code is pulled
      - main

jobs:
  test:
    # using ubuntu for CI environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      # Set up Python for the environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        # Upgrade pip
        python -m pip install --upgrade pip  
        # Install dependencies from requirements.txt
        pip install -r requirements.txt  

    - name: Run Unit Tests
      run:
        # run all tests in tests directory
        python -m unittest discover tests/
